# Why we need Attention mechanism

## The problem with modeling long sequences

Well, before the attention mechanism, architectures like RNN (encoder + decoder) were used in a sequence to sequence tasks like machine translation, however they had some noticeable problems.
The encoder part of the architecture takes the each part of the input, then processes it into a hidden state (memory cell), the decoder then takes the hidden state to produce the output (the hidden state here plays the role of the embeddings).

The issue here is that the decoder cannot access earlier hidden state during the decoding phase so it solely relies on the **current** hidden state.

And this was the reason the **Attetion mechanism** was introduced.

## Capturing data dependencies

One shortcoming for the RNN is that it must remember entire encoded text in a single hidden state before passing it to the decoder
*Bahdanau attention* was introduces that made the decoder selectively access different parts of the input sequence at each step 

The transformer architecture came in afterwards with a self-attention mechanism inspired by the *Bahdanau attention mechanism*
 - Self-attention is a mechanism that allows each position in the input sequence to attend to all positions in the same sequence when computing the representation of a sequence.


## Attending to different parts of the input with self-attention

in self-attention, the term “self” means that each element of a sequence (e.g., a word) pays attention to other elements within the same sequence to understand context and relationships. It learns how different parts of the input relate to each other, unlike traditional attention, which models relationships between two different sequences (e.g., input and output in seq2seq models).

### Simple self-attention mechanism without trainable weights

In self-attention, our goal is to calcualte a context vector z<sup>(i)</sup> for each element x<sup>(i)</sup> in the input sequence. A context vector can be interpreted as an enriched embedding vector. The importance or contribution of each input element for computing z<sup>2</sup> for example is determined by the attention weights α<sub>21</sub> to α<sub>2T</sub>. When computing z<sup>2</sup>, the attention weights are calculated with respect to input element x<sup>2</sup> and all other inputs.

<div align="center">
    <img src="self-attention.png" width="600">
</div>

This enhanced context vector, z<sup>2</sup>, is an embedding that contains information about x<sup>(2)</sup> and all other input elements x<sup>(1)</sup>to x<sup>(T)</sup>.

In self-attention, context vectors play a crucial role. Their purpose is to create enriched representations of each element in an input sequence (like a sentence) by incorporating
information from all other elements in the sequence

In [1]:
import torch

inputs = torch.tensor(
    [
        [0.43, 0.15, 0.89],  # Your (x^1)
        [0.55, 0.87, 0.66],  # journey (x^2)
        [0.57, 0.85, 0.64],  # starts (x^3)
        [0.22, 0.58, 0.33],  # with (x^4)
        [0.77, 0.25, 0.10],  # one (x^5)
        [0.05, 0.80, 0.55],
    ]  # step (x^6)
)

<div align="center">
    <img src="attention-weight.png" width="650">
</div>

We calculate the intermediate attention scores between the query token and each input token. We determine these scores by computing the dot product of the query, x<sup>2</sup> , with every other input token

In [2]:
query = inputs[1]

attn_scores_2 = torch.empty(inputs.shape[0])
for i, x_i in enumerate(inputs):
    attn_scores_2[i] = torch.dot(query, x_i)

attn_scores_2

tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865])

After computing the attention scores ω<sub>21</sub> to ω<sub>2T</sub> with respect to the input query x<sup>(2)</sup> , the next step is to obtain the attention weights α<sub>21</sub> to α<sub>2T</sub> by normalizing the attention scores
The goal is to obtain attention weights that sum up to 1

In [3]:
attn_weights_2_tmp = attn_scores_2 / attn_scores_2.sum()

print(f"Attention weights: {attn_weights_2_tmp}")
print(f"Sum: {attn_weights_2_tmp.sum()}")

Attention weights: tensor([0.1455, 0.2278, 0.2249, 0.1285, 0.1077, 0.1656])
Sum: 1.0000001192092896


In practice, it's more common and advisable to use the softmax function for normalization. This approach is better at managing extreme values and offers more favorable gradient properties during training, the softmax function ensures that the attention weights are always positive.
This makes the output interpretable as probabilities or relative importance

In [4]:
def softmax_naive(x):
    return torch.exp(x) / torch.exp(x).sum(dim=0)

attn_weights_2_naive = softmax_naive(attn_scores_2)

print(f"Attention weights: {attn_weights_2_naive}")
print(f"Sum: {attn_weights_2_naive.sum()}")

Attention weights: tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])
Sum: 1.0


This softmax we implemented may encounter numerical instability problems, such as overflow or underflow when dealing with large or small inputs, in practice is advisable to use pytoch implementation

In [5]:
attn_weights_2 = torch.softmax(attn_scores_2, dim=0)

print(f"Attention weights: {attn_weights_2}")
print(f"Sum: {attn_weights_2.sum()}")

Attention weights: tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])
Sum: 1.0


In [6]:
query = inputs[1] # 2nd input token is the query
context_vec_2 = torch.zeros(query.shape)
for i,x_i in enumerate(inputs):
    context_vec_2 += attn_weights_2[i]*x_i
print(context_vec_2)


tensor([0.4419, 0.6515, 0.5683])


### Computing attention weights for all input tokens

In [7]:
inputs

tensor([[0.4300, 0.1500, 0.8900],
        [0.5500, 0.8700, 0.6600],
        [0.5700, 0.8500, 0.6400],
        [0.2200, 0.5800, 0.3300],
        [0.7700, 0.2500, 0.1000],
        [0.0500, 0.8000, 0.5500]])

In [8]:
attn_scores = torch.empty(6, 6)
for i, x_i in enumerate(inputs):
    for j, x_j in enumerate(inputs):
        attn_scores[i, j] = torch.dot(x_i, x_j)
print(attn_scores)

tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])


because python loops are generally slow, we need to use matrix multiplication to achieve the same results

In [9]:
attn_scores = inputs @ inputs.T
print(attn_scores)

tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])


In [10]:
attn_weights = torch.softmax(attn_scores, dim=-1)
print(attn_weights)

tensor([[0.2098, 0.2006, 0.1981, 0.1242, 0.1220, 0.1452],
        [0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581],
        [0.1390, 0.2369, 0.2326, 0.1242, 0.1108, 0.1565],
        [0.1435, 0.2074, 0.2046, 0.1462, 0.1263, 0.1720],
        [0.1526, 0.1958, 0.1975, 0.1367, 0.1879, 0.1295],
        [0.1385, 0.2184, 0.2128, 0.1420, 0.0988, 0.1896]])


In [11]:
inputs

tensor([[0.4300, 0.1500, 0.8900],
        [0.5500, 0.8700, 0.6600],
        [0.5700, 0.8500, 0.6400],
        [0.2200, 0.5800, 0.3300],
        [0.7700, 0.2500, 0.1000],
        [0.0500, 0.8000, 0.5500]])

In [12]:
all_context_vector = attn_weights @ inputs
print(all_context_vector)

tensor([[0.4421, 0.5931, 0.5790],
        [0.4419, 0.6515, 0.5683],
        [0.4431, 0.6496, 0.5671],
        [0.4304, 0.6298, 0.5510],
        [0.4671, 0.5910, 0.5266],
        [0.4177, 0.6503, 0.5645]])


## Implementing self-attention with trainable weights

We will implement the self-attention mechanism step by step by introducing the three trainable weight matrices W<sub>q</sub>, W<sub>k</sub> and W<sub>v</sub>

<div align="center">
    <img src="qkv.png" width="650">
</div>

In [13]:
x_2 = inputs[1]           # Second input element
d_in = inputs.shape[1]    # Input embedding size
d_out = 2               # Output embedding size

# NOTE: in gpt-like models the input/output embedding sizes are usually the same, but for better illustration we chose different values

In [14]:
torch.manual_seed(123)
W_query = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)
W_key = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)
W_value = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)

print("Query matrix weights: ", W_query)
print("Key matrix weights: ", W_query)
print("Value matrix weights: ", W_value)

Query matrix weights:  Parameter containing:
tensor([[0.2961, 0.5166],
        [0.2517, 0.6886],
        [0.0740, 0.8665]])
Key matrix weights:  Parameter containing:
tensor([[0.2961, 0.5166],
        [0.2517, 0.6886],
        [0.0740, 0.8665]])
Value matrix weights:  Parameter containing:
tensor([[0.0756, 0.1966],
        [0.3164, 0.4017],
        [0.1186, 0.8274]])


In [15]:
x_2

tensor([0.5500, 0.8700, 0.6600])

In [16]:
query_2 = x_2 @ W_query
key_2 = x_2 @ W_key
value_2 = x_2 @ W_value

print(query_2)

tensor([0.4306, 1.4551])


In [17]:
inputs, W_key

(tensor([[0.4300, 0.1500, 0.8900],
         [0.5500, 0.8700, 0.6600],
         [0.5700, 0.8500, 0.6400],
         [0.2200, 0.5800, 0.3300],
         [0.7700, 0.2500, 0.1000],
         [0.0500, 0.8000, 0.5500]]),
 Parameter containing:
 tensor([[0.1366, 0.1025],
         [0.1841, 0.7264],
         [0.3153, 0.6871]]))

In [18]:
keys = inputs @ W_key
values = inputs @ W_value

print("Keys shape: ", keys.shape)
print("Values shape: ", values.shape)

Keys shape:  torch.Size([6, 2])
Values shape:  torch.Size([6, 2])


The second step is now to compute the attention scores, as shown

<div align="center">
    <img src="attn_score_qkv.png" width="650">
</div>

In [19]:
attn_score_22 = keys[1].dot(query_2)
print(attn_score_22)

tensor(1.8524)


In [20]:
query_2

tensor([0.4306, 1.4551])

In [21]:
keys.T

tensor([[0.3669, 0.4433, 0.4361, 0.2408, 0.1827, 0.3275],
        [0.7646, 1.1419, 1.1156, 0.6706, 0.3292, 0.9642]])

In [22]:
attn_scores_2 = query_2 @ keys.T
print(attn_scores_2)

tensor([1.2705, 1.8524, 1.8111, 1.0795, 0.5577, 1.5440])


Now we need to normalize the attention scores to obtain the attention weights

<div align="center">
    <img src="attn_score_norm_qkv.png" width="650">
</div>

we compute the attention weights by scaling the attention scores and using the softmax function we used earlier. The difference to earlier is that we now scale the attention scores by dividing them by the square root of the embedding dimension of the keys

In [23]:
d_k = keys.shape[-1]
attn_weights_2 = torch.softmax(attn_scores_2 / d_k**0.5, dim=-1)
print(attn_weights_2)

tensor([0.1500, 0.2264, 0.2199, 0.1311, 0.0906, 0.1820])


The reason for the normalization by the embedding dimension size is to improve the training performance by avoiding small gradients. For instance, when scaling up the embedding dimension, which is typically greater than thousand for GPT-like LLMs, large dot products can result in very small gradients during backpropagation due to the softmax function applied to them. As dot products increase, the softmax function
behaves more like a step function, resulting in gradients nearing zero. These small gradients can drastically slow down learning or cause training to stagnate.

The scaling by the square root of the embedding dimension is the reason why this self-attention mechanism is also called scaled-dot product attention.


Now, the final step is to compute the context vectors

<div align="center">
    <img src="context_vec_qkv.png" width="650">
</div>

In [24]:
values

tensor([[0.1855, 0.8812],
        [0.3951, 1.0037],
        [0.3879, 0.9831],
        [0.2393, 0.5493],
        [0.1492, 0.3346],
        [0.3221, 0.7863]])

In [25]:
attn_weights_2

tensor([0.1500, 0.2264, 0.2199, 0.1311, 0.0906, 0.1820])

In [26]:
context_vec_2 = attn_weights_2 @ values
context_vec_2

tensor([0.3061, 0.8210])

**WHY QUERY, KEY, AND VALUE?**

The terms `key`, `query`, and `value` in the context of attention mechanisms are
borrowed from the domain of information retrieval and databases, where similar
concepts are used to store, search, and retrieve information.

A "query" is analogous to a search query in a database. It represents the current
item (e.g., a word or token in a sentence) the model focuses on or tries to
understand. The query is used to probe the other parts of the input sequence to
determine how much attention to pay to them.

The "key" is like a database key used for indexing and searching. In the attention
mechanism, each item in the input sequence (e.g., each word in a sentence) has an
associated key. These keys are used to match with the query.

The "value" in this context is similar to the value in a key-value pair in a database. It
represents the actual content or representation of the input items. Once the model
determines which keys (and thus which parts of the input) are most relevant to the
query (the current focus item), it retrieves the corresponding values.


### Implementing a compact self-attention Python class

In [27]:
import torch.nn as nn

class SelfAttentionV1(nn.Module):
    def __init__(self, d_in, d_out):
        super().__init__()
        self.d_in = d_in
        self.d_out = d_out
        self.W_query = nn.Parameter(torch.rand(d_in, d_out))
        self.W_key   = nn.Parameter(torch.rand(d_in, d_out))
        self.W_value = nn.Parameter(torch.rand(d_in, d_out))

    def forward(self, x):
        queries = x @ self.W_query
        keys    = x @ self.W_key
        values  = x @ self.W_value

        attn_scores = queries @ keys.T
        attn_weights = torch.softmax(attn_scores / keys.shape[-1]**0.5, dim=-1)

        context_vec = attn_weights @ values

        return context_vec

In [28]:
torch.manual_seed(123)

sa_v1 = SelfAttentionV1(d_in, d_out)
print(sa_v1(inputs))

tensor([[0.2996, 0.8053],
        [0.3061, 0.8210],
        [0.3058, 0.8203],
        [0.2948, 0.7939],
        [0.2927, 0.7891],
        [0.2990, 0.8040]], grad_fn=<MmBackward0>)


Self-attention mechanism summary

<div align="center">
    <img src="att_weight_kqv_summary.png" width="650">
</div>

We can improve the SelfAttentionV1 By using PyTorch's `nn.Linear` layers, which effectively perform matrix multiplication when the bias units are disabled. Additionally, a significant advantage of using nn.Linear instead of `nn.Parameter(torch.rand(...))` is that nn.Linear has an **optimized weight initialization scheme, contributing to more stable and effective model training**

In [29]:
import torch.nn as nn

class SelfAttentionV2(nn.Module):
    def __init__(self, d_in, d_out, qkv_bias=False):
        super().__init__()
        self.d_in = d_in
        self.d_out = d_out
        self.W_query = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_key   = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_value = nn.Linear(d_in, d_out, bias=qkv_bias)

    def forward(self, x):
        queries = self.W_query(x)
        keys    = self.W_key(x)
        values  = self.W_value(x)

        attn_scores = queries @ keys.T
        attn_weights = torch.softmax(attn_scores / keys.shape[-1]**0.5, dim=-1)

        context_vec = attn_weights @ values

        return context_vec

In [30]:
torch.manual_seed(789)
sa_v2 = SelfAttentionV2(d_in, d_out)
print(sa_v2(inputs))

tensor([[-0.0739,  0.0713],
        [-0.0748,  0.0703],
        [-0.0749,  0.0702],
        [-0.0760,  0.0685],
        [-0.0763,  0.0679],
        [-0.0754,  0.0693]], grad_fn=<MmBackward0>)


## Hiding future words with causal attention

Causal attention or masked attention, is a specialized form of self-attention that restricts a model to only consider previous and current inputs in a sequence when processing any given token. This is in contrast to the standard self-attention mechanism, which allows access to the entire input sequence at once.

To achieve this in GPT-like LLMs, for each token processed, we mask out the future tokens, which come after the current token in the input text
As illustrated, we mask out the attention weights above the diagonal, and **we normalize the non-masked attention weights**
<div align="center">
    <img src="masked-attention.png" width="650">
</div>

we compute the attention weights using the softmax function as we have done in previous sections

In [31]:
queries = sa_v2.W_query(inputs)
keys    = sa_v2.W_key(inputs)

attn_scores = queries @ keys.T
attn_weights = torch.softmax(attn_scores / keys.shape[-1]**0.5, dim=-1)

print(attn_weights)

tensor([[0.1921, 0.1646, 0.1652, 0.1550, 0.1721, 0.1510],
        [0.2041, 0.1659, 0.1662, 0.1496, 0.1665, 0.1477],
        [0.2036, 0.1659, 0.1662, 0.1498, 0.1664, 0.1480],
        [0.1869, 0.1667, 0.1668, 0.1571, 0.1661, 0.1564],
        [0.1830, 0.1669, 0.1670, 0.1588, 0.1658, 0.1585],
        [0.1935, 0.1663, 0.1666, 0.1542, 0.1666, 0.1529]],
       grad_fn=<SoftmaxBackward0>)


create a mask where the values above the diagonal are zero

In [32]:
context_length = attn_scores.shape[0]
attention_mask = torch.tril(torch.ones(context_length, context_length))
attention_mask

tensor([[1., 0., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1.]])

multiply the mask with the attention weights to zero out the values above the diagonal

In [33]:
masked_weights = attention_mask * attn_weights
print(masked_weights)

tensor([[0.1921, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2041, 0.1659, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2036, 0.1659, 0.1662, 0.0000, 0.0000, 0.0000],
        [0.1869, 0.1667, 0.1668, 0.1571, 0.0000, 0.0000],
        [0.1830, 0.1669, 0.1670, 0.1588, 0.1658, 0.0000],
        [0.1935, 0.1663, 0.1666, 0.1542, 0.1666, 0.1529]],
       grad_fn=<MulBackward0>)


renormalize the attention weights to sum up to 1 again in each row

In [34]:
row_sums = masked_weights.sum(dim=1, keepdim=True)
masked_weights_norm = masked_weights / row_sums
print(masked_weights_norm)

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5517, 0.4483, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3800, 0.3097, 0.3103, 0.0000, 0.0000, 0.0000],
        [0.2758, 0.2460, 0.2462, 0.2319, 0.0000, 0.0000],
        [0.2175, 0.1983, 0.1984, 0.1888, 0.1971, 0.0000],
        [0.1935, 0.1663, 0.1666, 0.1542, 0.1666, 0.1529]],
       grad_fn=<DivBackward0>)


we can take advantage of a mathematical property of the softmax function and implement the computation of the masked attention weights more efficiently in fewer steps

In [35]:
mask = torch.triu(torch.ones(context_length, context_length), diagonal=1)
mask

tensor([[0., 1., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1., 1.],
        [0., 0., 0., 1., 1., 1.],
        [0., 0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0.]])

In [36]:
mask.bool()

tensor([[False,  True,  True,  True,  True,  True],
        [False, False,  True,  True,  True,  True],
        [False, False, False,  True,  True,  True],
        [False, False, False, False,  True,  True],
        [False, False, False, False, False,  True],
        [False, False, False, False, False, False]])

In [37]:
# Fills elements of tensor (self) with value(-torch.ing) where mask is True
masked = attn_scores.masked_fill(mask.bool(), -torch.inf)
masked

tensor([[0.2899,   -inf,   -inf,   -inf,   -inf,   -inf],
        [0.4656, 0.1723,   -inf,   -inf,   -inf,   -inf],
        [0.4594, 0.1703, 0.1731,   -inf,   -inf,   -inf],
        [0.2642, 0.1024, 0.1036, 0.0186,   -inf,   -inf],
        [0.2183, 0.0874, 0.0882, 0.0177, 0.0786,   -inf],
        [0.3408, 0.1270, 0.1290, 0.0198, 0.1290, 0.0078]],
       grad_fn=<MaskedFillBackward0>)

In [38]:
attn_weights = torch.softmax(masked / keys.shape[-1]**0.5, dim=1)
attn_weights

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5517, 0.4483, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3800, 0.3097, 0.3103, 0.0000, 0.0000, 0.0000],
        [0.2758, 0.2460, 0.2462, 0.2319, 0.0000, 0.0000],
        [0.2175, 0.1983, 0.1984, 0.1888, 0.1971, 0.0000],
        [0.1935, 0.1663, 0.1666, 0.1542, 0.1666, 0.1529]],
       grad_fn=<SoftmaxBackward0>)

We could now use the modified attention weights to compute the context vectors via `context_vec = attn_weights @ values`

### Masking additional attention weights with dropout

In the transformer architecture dropout in the attention is applied to two areas: after calculating the attention scores or after applying the attention weights to the value vectors

Here we will apply a dropout mask after calculating the attention weights (it's more common variant in practice).

<img src="dropout-attention.png" width="650">

In [39]:
torch.manual_seed(123)

dropout = nn.Dropout(0.5)
example = torch.ones(6,6)
print(dropout(example))

tensor([[2., 2., 0., 2., 2., 0.],
        [0., 0., 0., 2., 0., 2.],
        [2., 2., 2., 2., 0., 2.],
        [0., 2., 2., 0., 0., 2.],
        [0., 2., 0., 2., 0., 2.],
        [0., 2., 2., 2., 2., 0.]])


So with a rate of 50%, half of the attention weights are randomly set to zero, to compensate the reduction in active elements, the remaining values are scaled up by a factor of 1/0.5=2, `value/(1-p)`

This scaling is crucial to maintain the overall balance of the attention weights, ensuring that the average influence of the attention mechanism remains consistent during both the training and inference phases.

In [40]:
torch.manual_seed(123)
dropout(attn_weights)

tensor([[2.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.7599, 0.6194, 0.6206, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.4921, 0.4925, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.3966, 0.0000, 0.3775, 0.0000, 0.0000],
        [0.0000, 0.3327, 0.3331, 0.3084, 0.3331, 0.0000]],
       grad_fn=<MulBackward0>)

### Implementing a compact causal attention class

Before we begin, one more thing is to ensure that the code can handle batches
consisting of more than one input so that the CausalAttention class supports the batch
outputs

In [41]:
batch = torch.stack((inputs, inputs+1), dim=0)
batch, batch.shape

(tensor([[[0.4300, 0.1500, 0.8900],
          [0.5500, 0.8700, 0.6600],
          [0.5700, 0.8500, 0.6400],
          [0.2200, 0.5800, 0.3300],
          [0.7700, 0.2500, 0.1000],
          [0.0500, 0.8000, 0.5500]],
 
         [[1.4300, 1.1500, 1.8900],
          [1.5500, 1.8700, 1.6600],
          [1.5700, 1.8500, 1.6400],
          [1.2200, 1.5800, 1.3300],
          [1.7700, 1.2500, 1.1000],
          [1.0500, 1.8000, 1.5500]]]),
 torch.Size([2, 6, 3]))

This results in a 3D tensor consisting of 2 input texts with 6 tokens each, where each token
is a 3-dimensional embedding vector

In [42]:
class CausalAttention(nn.Module):
    def __init__(self, d_in, d_out, context_length, dropout, qkv_bias=False):
        super().__init__()
        self.d_in = d_in
        self.d_out = d_out
        self.W_query = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_key   = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_value = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.dropout = nn.Dropout(dropout)
        self.register_buffer(
            'mask',
            torch.triu(torch.ones(context_length, context_length), diagonal=1)
        )

    def forward(self, x):
        b, num_tokens, d_in = x.shape
        queries = self.W_query(x)
        keys    = self.W_key(x)
        values  = self.W_value(x)

        attn_scores = queries @ keys.transpose(1,2)
        # NOTE: operations with a trailing underscore are performed in-place, avoiding unnecessary memory copies
        attn_scores.masked_fill_(
            # NOTE: ensure that mask matches the actual sequence length by adding :num_tokens slicing
            self.mask.bool()[:num_tokens, :num_tokens], -torch.inf
        )
        attn_weights = torch.softmax(attn_scores / keys.shape[-1]**0.5, dim=-1)
        attn_weights = self.dropout(attn_weights)

        context_vec = attn_weights @ values
        return context_vec

In [43]:
torch.manual_seed(123)
context_length = batch.shape[1]
ca = CausalAttention(d_in, d_out, context_length, 0.2)
context_vecs = ca(batch)
context_vecs.shape

torch.Size([2, 6, 2])

## Extending single-head attention to multi-head attention

The term "multi-head" refers to dividing the attention mechanism into multiple "heads,"
each operating independently. In this context, a single causal attention module can be
considered single-head attention, where there is only one set of attention weights
processing the input sequentially.


<img src="mult-head-stacking.png" width="600" >

In [44]:
class MultiHeadAttentionWrapper(nn.Module):
    def __init__(self, d_in, d_out, context_length, dropout, num_heads, qkv_bias=False):
        super().__init__()
        self.heads = nn.ModuleList(
            [
                CausalAttention(d_in, d_out, context_length, dropout, qkv_bias) for _ in range(num_heads)
            ]
        )
    
    def forward(self, x):
        return torch.cat([head(x) for head in self.heads], dim=-1)

In [45]:
m_h = MultiHeadAttentionWrapper(d_in, d_out, context_length, dropout=0.2, num_heads=2)
context_vecs = m_h(batch)

In [46]:
context_vecs.shape

torch.Size([2, 6, 4])

In this section, we implemented a MultiHeadAttentionWrapper that combined multiple
single-head attention modules. However, note that these are processed sequentially via
`[head(x) for head in self.heads]` in the forward method. We can improve this
implementation by processing the heads in parallel. One way to achieve this is by
computing the outputs for all attention heads simultaneously via matrix multiplication, as
we will explore in the next section.

### Implementing multi-head attention with weight splits

Instead of maintaining two separate classes, `MultiHeadAttentionWrapper` and
`CausalAttention`, we can combine both of these concepts into a single
`MultiHeadAttention` class. Also, in addition to just merging the
`MultiHeadAttentionWrapper` with the `CausalAttention` code, we will make some other
modifications to implement multi-head attention more efficiently.
In the `MultiHeadAttentionWrapper`, multiple heads are implemented by creating a list
of `CausalAttention` objects (self.heads), each representing a separate attention head.
The `CausalAttention` class independently performs the attention mechanism, and the
results from each head are concatenated. In contrast, the following MultiHeadAttention
class integrates the multi-head functionality within a single class. It splits the input into
multiple heads by reshaping the projected query, key, and value tensors and then combines
the results from these heads after computing attention

In [ ]:
class MultiHeadAttention(nn.Module):
    def __init__(self, d_in, d_out, context_length, dropout, num_heads, qkv_bias=False):
        super().__init__()
        assert d_out % num_heads == 0, "d_out must be divisible by num_heads"

        self.d_out = d_out
        self.num_heads = num_heads
        self.head_dim = d_out // num_heads  # Reduce the projection dim to match desired output dim

        self.W_query = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_key   = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_value = nn.Linear(d_in, d_out, bias=qkv_bias)

        self.out_proj = nn.Linear(d_out, d_out)  # Use a Linear layer to combine head outputs
        self.dropout = nn.Dropout(dropout)
        self.register_buffer(
            "mask",
            torch.triu(torch.ones(context_length, context_length), diagonal=1)
        )

    def forward(self, x):
        b, num_tokens, d_in = x.shape

        queries = self.W_query(x)  # (b, num_tokens, d_out)
        keys    = self.W_key(x)    # (b, num_tokens, d_out)
        values  = self.W_value(x)  # (b, num_tokens, d_out)

        # We implicitly split the matrix by adding a `num_heads` dimension. Then we unroll last dim: (b, num_tokens, d_out) -> (b, num_tokens, num_heads, head_dim)
        # NOTE: each head contains its own kqv matrices, the thing is that self.W_query contains all num_heads weights because we used d_out = num_heads * head_dim
        queries = queries.view(b, num_tokens, self.num_heads, self.head_dim)
        keys    = keys.view(b, num_tokens, self.num_heads, self.head_dim)
        values  = values.view(b, num_tokens, self.num_heads, self.head_dim)

        # Transpose from shape (b, num_tokens, num_heads, head_dim) to (b, num_heads, num_tokens, head_dim)
        queries = queries.transpose(1,2)
        keys    = keys.transpose(1,2)
        values  = values.transpose(1, 2)

        # Compute dot product for each head
        # (b, heads, num_tokens, num_tokens)
        attn_scores = queries @ keys.transpose(2, 3)
        # Mask truncated to the number of tokens
        mask_bool = self.mask.bool()[:num_tokens, :num_tokens]
        # Use the mask to fill attention scores
        attn_scores.masked_fill_(mask_bool, -torch.inf)

        attn_weights = torch.softmax(attn_scores / keys.shape[-1]**0.5, dim=-1)
        attn_weights = self.dropout(attn_weights)

        # Tensor shape: (b, num_tokens, n_heads, head_dim)
        context_vec = (attn_weights @ values).transpose(1, 2)
        # Combine heads, where self.d_out = self.num_heads * self.head_dim
        context_vec = context_vec.contiguous().view(b, num_tokens, self.d_out)
        # Add an optional linear projection
        context_vec = self.out_proj(context_vec)
        return context_vec

On a big-picture level, in the previous MultiHeadAttentionWrapper, we stacked
multiple single-head attention layers that we combined into a multi-head attention layer.
The MultiHeadAttention class takes an integrated approach. It starts with a multi-head
layer and then internally splits this layer into individual attention heads

 In the MultiheadAttentionWrapper class with two attention heads, we initialized two weight
matrices Wq1 and Wq2 and computed two query matrices Q1 and Q2 as illustrated at the top of this figure. In
the MultiheadAttention class, we initialize one larger weight matrix Wq
, only perform one matrix
multiplication with the inputs to obtain a query matrix Q, and then split the query matrix into Q1 and Q2 as
shown at the bottom of this figure. We do the same for the keys and values, which are not shown to reduce
visual clutter

<img src="heads-splitting.png" width="700" >

# Page 108